# Generated by Django 5.1.7 on 2025-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_4_digit_account_number', models.CharField(max_length=4)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('utr', models.CharField(max_length=12, unique=True)),
                ('trid', models.CharField(max_length=13, unique=True)),
                ('self_account_number', models.CharField(max_length=20)),
                ('screenshot_photo', models.ImageField(blank=True, default=None, upload_to='')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
