# Generated by Django 5.1.7 on 2025-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winbuzzSS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_screenshot',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
