# Generated by Django 5.1.7 on 2025-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winbuzzSS', '0002_deposit_screenshot_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_screenshot',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
